### ISSUE TITLE
Documentation clarification for AppStoreApp recipes

### ISSUE THREAD

**Issue by jazzace** [autopkg/nmcspadden-recipes#11]
In the README file for your recipes, you provide details on how to install pyasn1 (for AppStoreApp recipes), giving two different methods. In the easy_install method, it should be clarified that if ~/Library/Python/2.7/lib/python/site-packages/ does not yet exist, it must be created manually before running the easy_install command provided. (Otherwise, the temptation is to install it in /Library/Python/2.7/lib/python/site-packages/ instead, which does exist, but an easy_install to that location fails, even with sudo.)

**Comment by nmcspadden** [comment]
Fixed with https://github.com/autopkg/nmcspadden-recipes/commit/3a77ef04b0b9e19327be02914ede63774c8ffa64.

**Comment by timsutton** [comment]
Sorry for missing that step when I gave the instructions for `easy_install`! That directory already existed on my machine and I usually use `pip` so hadn't run into that issue before.
