### ISSUE TITLE
unitywebplayer.munki parent recipe correction.

### ISSUE THREAD

**Issue by eahrold** [autopkg/nmcspadden-recipes#12]
@nmcspadden, I just noticed that`unitywebplayer.munki`  has `unitywebplayer.download.recipe` as the parent, but it looks like it should be `com.github.nmcspadden.unitywebplayer.download.recipe`, just wanted to let you know.

**Comment by nmcspadden** [comment]
Thanks, fixed with https://github.com/autopkg/nmcspadden-recipes/commit/4e967e53169ad298fbee29c505065b2df9810187.
