### ISSUE TITLE
GoogleEarth Pro version mismatch actual vs munki

### ISSUE THREAD

**Issue by BestMacsBen** [autopkg/nmcspadden-recipes#13]
I've noticed that the version number that gets fed into munki doesn't match the version reported by the app or in it's info.plist. Current today is 7.1.5.1557 but when it gets imported into munki it gets tagged 7.1.2. Not sure where it's getting the 7.1.2 from.

**Comment by timsutton** [comment]
I'm guessing that the Google Earth Pro recipe(s) might need an update similar to [what we did](https://github.com/autopkg/recipes/commit/f9c7b9306cf758b49602e24224d13583df0179cd) to the recipes in autopkg/recipes.

For the version specifically:
https://github.com/autopkg/recipes/blob/f9c7b9306cf758b49602e24224d13583df0179cd/GoogleEarth/GoogleEarth.munki.recipe#L111-L134

**Comment by nmcspadden** [comment]
Fixed with https://github.com/autopkg/nmcspadden-recipes/commit/4c419f01e46fd46c3ed8b730f51767461e223b6d.
