### ISSUE TITLE
Minecraft will not open: Minecraft updater error

### ISSUE THREAD

**Issue by jakerundall** [autopkg/nmcspadden-recipes#15]
When I uses this recipe (via Minecraft.munki.recipe) to install Minecraft, the app will not open.  The error I get is:
Minecraft updater
Unable to start Minecraft, if you are running from a dmg, please drag to Applications and try again

It seems that this is related to permissions, because if I chown -R the app to the user who will run it, it works fine.  I believe this is a known issue with Minecraft in a multi-user environment, so it's not an issue with this recipe, per se.  But I'm wondering if you have thoughts or workarounds.

Perhaps not unrelated (since the error is labeled "Minecraft updater"), this recipe is downloading/installing an app with CFBundleShortVersionString = 272 while the current version (from minecraft.net) has CFBundleShortVersionString = 285.  So maybe the answer is simply updating the Minecraft.download.recipe to get the newer version of the app and the supporting files?  The app itself seems to be available from https://launcher.mojang.com/download/Minecraft.dmg.  I'm not sure where the "runtime" and "Launcher" components come from.

I'll also add that when I manually download and install the current Minecraft app (v285, chown'd to my standard user who is running it), it goes through the following setup steps:
Updating Minecraft
Downloading runtime
Setting up runtime
Downloading launcher
Unpacking launcher

With the "Updating Minecraft" step showing up, it seems likely that Minecraft requires that the current user have write permissions on the app so that it can be updated.  In that case, there's not a lot of hope for Minecraft in a multi-user environment, unless you want to make it writable by everyone or install it per user.

Finally, I'm wondering if a custom Launcher would be possible for this app, similar to what you've designed for MinecraftEdu.

Thanks,

Jake

**Comment by nmcspadden** [comment]
Unfortunately, Minecraft has completely changed how the installer works
since I wrote this recipe; this method simply doesn't work anymore.

I have a work in progress solution, but it might be better for me to simply
pull Minecraft from my repo until that's ready to go. As I no longer have
to deploy Minecraft, this is not a priority for me.

Annoyingly, Minecraft still assumes that it's installing for the *only*
user of the system, and doesn't even pretend to work with multiple users.
The best solution I've found for mass-deployment is still to put up a
launch agent that copies the appropriate pieces into the user's Library,
similarly to what I did for MinecraftEdu.

For now, this will languish a bit until I find the time to address it.
Sorry for the inconvenience.

On Tue, Oct 20, 2015 at 12:19 PM, jakerundall <notifications@github.com>
wrote:

> When I uses this recipe (via Minecraft.munki.recipe) to install Minecraft,
> the app will not open. The error I get is:
> Minecraft updater
> Unable to start Minecraft, if you are running from a dmg, please drag to
> Applications and try again
>
> It seems that this is related to permissions, because if I chown -R the
> app to the user who will run it, it works fine. I believe this is a known
> issue with Minecraft in a multi-user environment, so it's not an issue with
> this recipe, per se. But I'm wondering if you have thoughts or workarounds.
>
> Perhaps not unrelated (since the error is labeled "Minecraft updater"),
> this recipe is downloading/installing an app with
> CFBundleShortVersionString = 272 while the current version (from
> minecraft.net) has CFBundleShortVersionString = 285. So maybe the answer
> is simply updating the Minecraft.download.recipe to get the newer version
> of the app and the supporting files? The app itself seems to be available
> from https://launcher.mojang.com/download/Minecraft.dmg. I'm not sure
> where the "runtime" and "Launcher" components come from.
>
> I'll also add that when I manually download and install the current
> Minecraft app (v285, chown'd to my standard user who is running it), it
> goes through the following setup steps:
> Updating Minecraft
> Downloading runtime
> Setting up runtime
> Downloading launcher
> Unpacking launcher
>
> With the "Updating Minecraft" step showing up, it seems likely that
> Minecraft requires that the current user have write permissions on the app
> so that it can be updated. In that case, there's not a lot of hope for
> Minecraft in a multi-user environment, unless you want to make it writable
> by everyone or install it per user.
>
> Finally, I'm wondering if a custom Launcher would be possible for this
> app, similar to what you've designed for MinecraftEdu.
>
> Thanks,
>
> Jake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/autopkg/nmcspadden-recipes/issues/15>.
>



-- 
--
Nick McSpadden
nmcspadden@gmail.com

**Comment by jakerundall** [comment]
No worries.  That's completely understandable.  I ended up going with a similar solution to what you describe for now, although it's a little more blunt: I just install the app in somewhere in /Library then use a LaunchAgent to copy the app into the user's home folder in ~/Applications.  If I deploy a new version compared to what they have, my LaunchAgent will update any existing installation in ~/Applications.  It's a little more wasteful but I wasn't quite sure what the necessary components were.  And it seemed like it would continue to work even if Minecraft changes things again.

**Comment by ItzLila** [comment]
Could you do a step by step to kind of 'fix' this probem, or do your solution. I attempted to do it but it's pretty hard to understand :+1:

**Comment by jakerundall** [comment]
Hi - I've installed 3 items: the app, a script to be run at the user level to copy the app (and also register it as trusted), and LaunchAgent to schedule the script at login. After installation, you may need to reboot to load the LaunchAgent (or at least log out).


1. Minecraft.app - I've put this in a custom directory:
/Library/LaunchAgentScripts/Minecraft_for_all_users


2. install_or_update_Minecraft.sh - I've also put this in the custom directory (perms should be 755):
/Library/LaunchAgentScripts/Minecraft_for_all_users

content is as follows:
#!/bin/bash

# Copies Minecraft.app to the user's home folder in ~/Applications
# and registers it as a trusted applications.

# If the user does not have an ~/Applications folder, create it.
if [ ! -f ~/Applications ]; then
	/bin/mkdir ~/Applications
fi

# If the user does not already have Minecraft in their ~/Applications folder, copy it there and trust it.
# Otherwise, check to see if their version is outdated and copy in the new one (and trust it) if that is the case.
if [ ! -f ~/Applications/Minecraft.app ]; then
	/usr/bin/ditto /Library/LaunchAgentScripts/Minecraft_for_all_users/Minecraft.app ~/Applications/Minecraft.app
	register_trusted_cmd="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -R -f -trusted"
	application=~/Applications/Minecraft.app
	$register_trusted_cmd "$application"

	exit 0
else
	vAvailableVersion=`/usr/bin/defaults read /Library/FAA/LaunchAgentScripts/Minecraft_for_all_users/Minecraft.app/Contents/Info.plist CFBundleShortVersionString`
	vUserVersion=`/usr/bin/defaults read ~/Applications/Minecraft.app/Contents/Info.plist CFBundleShortVersionString`

	if [ "$vUserVersion" -lt "$vAvailableVersion" ]; then
		/usr/bin/ditto /Library/LaunchAgentScripts/Minecraft_for_all_users/Minecraft.app ~/Applications/Minecraft.app			
		register_trusted_cmd="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -R -f -trusted"
		application=~/Applications/Minecraft.app
		$register_trusted_cmd "$application"
	fi

	exit 0
fi


3. com.mycorp.Minecraft_for_all_users.plist - This needs to be installed in the following location with perms = 644 and root:wheel ownership:
/Library/LaunchAgents

content is as follows:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.mycorp.Minecraft_for_all_users</string>
  <key>LimitLoadToSessionType</key>
  <array>
    <string>Aqua</string>
  </array>
  <key>ProgramArguments</key>
  <array>
    <string>/Library/LaunchAgentScripts/Minecraft_for_all_users/install_or_update_Minecraft.sh</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
</dict>
</plist>


You could also use outset instead of a LaunchAgent. If I were redesigning this that is what I'd do now. Let me know if you have any questions on this.

Jake

**Comment by jakerundall** [comment]
FYI, I've updated my recent reply. Lots of the code got interpreted as markup and displayed funny, so I've thrown the code on github and provided links instead.

Jake

**Comment by thallam08** [comment]
Still an issue …..
Caused by Minecraft trying to write to the application folder. Must have been developed for Windows. Unix systems should be able to run with read only application directories.

A hacked solution is to recursively change the group  of Minecraft.app folder to “staff”, and recursively enable group write access.

I’m sure a more targeted change is possible, but MS really needs to fix this.

**Comment by sgerodes** [comment]
Had this issue too on my mac. I solved it with chmoding the app to the user that will use the app.

sudo chown -R <user_that_will_use_minecraft> /Applications/Minecraft.app

Now it works perfectly

**Comment by thallam08** [comment]
Unfortunately your suggestion will only work if only one person uses the computer.

This error is the type of issue you'd expect from inexperienced programmers who have learnt to program in Windows 3.  Application directories should be read-only for normal users.  One Administrators should be able to write to application directories.
