### ISSUE TITLE
ChefDK download URL scheme changed again

### ISSUE THREAD

**Issue by kitzy** [autopkg/nmcspadden-recipes#21]
Looks like the URL to search should now be `https://downloads.chef.io/chefdk` and the regex string should now be `(files\/stable\/chefdk\/(.*?)\/mac_os_x\/%OS%\/chefdk-(.*?).dmg)`.

**Comment by kitzy** [comment]
The above regex string should work (https://regex101.com/r/rI4pQ1/7) but it doesn't appear to in Autopkg.

**Comment by kitzy** [comment]
I was able to get it working using `(files\/stable\/chefdk\/(\d\.\d\.\d)\/mac_os_x\/%OS%\/chefdk-(.*?).dmg)` however this will probably break as soon as there's 2 or more digits in any part of the version number.

**Comment by kitzy** [comment]
Adding a + after each /d should do the trick:

`(files\/stable\/chefdk\/(\d+\.\d+\.\d+)\/mac_os_x\/%OS%\/chefdk-(.*?).dmg)`

**Comment by timsutton** [comment]
Just curious, would something like Chef's [Omnitruck API](https://docs.chef.io/api_omnitruck.html) help to do this easier?

**Comment by timsutton** [comment]
i.e. https://omnitruck.chef.io/stable/chefdk/download?p=mac_os_x&pv=10.12&m=x86_64&v=latest

**Comment by kitzy** [comment]
That actually might be a better option.

**Comment by nmcspadden** [comment]
Fixed (temporarily, at least) in 53d0f35c6e9527b6b790f53c332de89a4e7a0f24.
